name: Release

on:
  push:
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      ref:
        required: false

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      BUILDER_VSN: ${{ steps.env_setup.outputs.BUILDER_VSN }}
      OTP_VSN: ${{ steps.env_setup.outputs.OTP_VSN }}
      ELIXIR_VSN: ${{ steps.env_setup.outputs.ELIXIR_VSN }}
      BUILDER: ${{ steps.env_setup.outputs.BUILDER }}
      EMQX_IMAGE: ${{ steps.env_setup.outputs.EMQX_IMAGE }}
      UBUNTU_VSN: ${{ steps.env_setup.outputs.UBUNTU_VSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Set up environment
        id: env_setup
        run: |
          source test/scripts/env.sh
          echo "BUILDER_VSN=$EMQX_BUILDER_VSN" | tee -a "$GITHUB_OUTPUT"
          echo "EMQX_OTP_VSN=$OTP_VSN" | tee -a "$GITHUB_OUTPUT"
          echo "OTP_VSN=$OTP_VSN" | tee -a "$GITHUB_OUTPUT"
          echo "ELIXIR_VSN=$ELIXIR_VSN" | tee -a "$GITHUB_OUTPUT"
          echo "BUILDER=$EMQX_BUILDER" | tee -a "$GITHUB_OUTPUT"
          echo "EMQX_IMAGE=$EMQX_IMAGE" | tee -a "$GITHUB_OUTPUT"
          echo "UBUNTU_VSN=$UBUNTU_VSN" | tee -a "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    container: ${{ needs.init.outputs.builder }}
    needs:
      - init
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: build
        run: |
          rebar3 escriptize
          cp _build/default/bin/emqx_data_converter ./
      - uses: actions/upload-artifact@v4.3.5
        with:
          name: emqx_data_converter
          path: emqx_data_converter
          retention-days: 1
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs:
      - init
      - build
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: emqx_data_converter
      - name: rename executable
        run: mv emqx_data_converter emqx_data_converter-ubuntu${{ needs.init.outputs.UBUNTU_VSN }}
      - name: Create Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: emqx-data-converter ${{ github.ref_name }}
          body: emqx-data-converter ${{ github.ref_name }}
          files: emqx_data_converter-*
          draft: ${{ github.event_name != 'tag' }}
          prerelease: ${{ github.event_name != 'tag' }}
